# CI for Xcode Builder

before_script:
  - uname -a
  - whoami
  - pwd
  - xcodebuild -list

build:
  tags:
    - iOS
  artifacts:
    paths:
      - artifacts/
  script:
    - SAFELOCATION=$(pwd) && echo $SAFELOCATION
    - rm -rf artifacts
    - mkdir artifacts    
    - bake.command
    # CLEAN UP JOBS
    - cd $SAFELOCATION
    - ls -la artifacts
    - for i in artifacts/*.deb; do dpkg -I $i; done

