# CI for Xcode Builder

before_script:
  - uname -a
  - whoami
  - pwd
  - xcodebuild -list

build:
  tags:
    - iOS
  script:
    - SAFELOCATION=$(pwd) && echo $SAFELOCATION
    - cd $SAFELOCATION
    - cd SpringBoardInjector/DesktopLyricOverlay && xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" MonkeyDevInstallOnProfiling="NO" MonkeyDevInstallOnAnyBuild="NO" MonkeyDevCopyOnBuild="NO" MonkeyDevClearUiCacheOnInstall="NO" MonkeyDevBuildPackageOnAnyBuild="YES"
    - cd $SAFELOCATION
    - cd NMRoutine/NeteaseMusicLyricProvider && xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" MonkeyDevInstallOnProfiling="NO" MonkeyDevInstallOnAnyBuild="NO" MonkeyDevCopyOnBuild="NO" MonkeyDevClearUiCacheOnInstall="NO" MonkeyDevBuildPackageOnAnyBuild="YES"




