# CI for Xcode Builder

before_script:
  - uname -a
  - whoami
  - pwd
  - xcodebuild -list

build:
  tags:
    - iOS
  artifacts:
    paths:
      - artifacts/
  script:
    - SAFELOCATION=$(pwd) && echo $SAFELOCATION
    - mkdir artifacts    

    # SpringBoad Injector
    - cd $SAFELOCATION
    - cd SpringBoardInjector/DesktopLyricOverlay
    - xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" MonkeyDevInstallOnProfiling="NO" MonkeyDevInstallOnAnyBuild="NO" MonkeyDevCopyOnBuild="NO" MonkeyDevClearUiCacheOnInstall="NO" MonkeyDevBuildPackageOnAnyBuild="YES"
    - cp Packages/*.deb $SAFELOCATION/artifacts/

    # NMRoutine
    - cd $SAFELOCATION
    - cd NMRoutine/NeteaseMusicLyricProvider
    - xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" MonkeyDevInstallOnProfiling="NO" MonkeyDevInstallOnAnyBuild="NO" MonkeyDevCopyOnBuild="NO" MonkeyDevClearUiCacheOnInstall="NO" MonkeyDevBuildPackageOnAnyBuild="YES"
    - cp Packages/*.deb $SAFELOCATION/artifacts/

    # CLEAN UP JOBS
    - cd $SAFELOCATION
    - ls -la artifacts
    - time

