# CI for Xcode Builder

before_script:
  - uname -a
  - whoami
  - pwd
  - xcodebuild -list

build:
  tags:
    - iOS
  script:
    - mkdir SpringBoardInjector/DesktopLyricOverlay/build/Release-iphoneos
    - cd SpringBoardInjector/DesktopLyricOverlay && xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" MonkeyDevInstallOnProfiling="NO" MonkeyDevInstallOnAnyBuild="NO" MonkeyDevCopyOnBuild="NO" MonkeyDevClearUiCacheOnInstall="NO" MonkeyDevBuildPackageOnAnyBuild="NO"



