# CI for Xcode Builder

before_script:
  - uname -a
  - whoami
  - pwd
  - xcodebuild -list

build:
  tags:
    - iOS
  artifacts:
    paths:
      - artifacts/
  script:
    - SAFELOCATION=$(pwd) && echo $SAFELOCATION
    - rm -rf artifacts
    - mkdir artifacts    

    # SpringBoad Injector
    - cd $SAFELOCATION/SpringBoardInjector/DesktopLyricOverlay
    - rm -rf Packages/*

    - xcodebuild clean build
        CODE_SIGN_IDENTITY=""
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_ENTITLEMENTS=""
        CODE_SIGNING_ALLOWED="NO"
        MonkeyDevInstallOnProfiling="NO"
        MonkeyDevInstallOnAnyBuild="NO"
        MonkeyDevCopyOnBuild="NO"
        MonkeyDevClearUiCacheOnInstall="NO"
        MonkeyDevBuildPackageOnAnyBuild="YES"
        | xcpretty

    - cp Packages/*.deb $SAFELOCATION/artifacts/

    # NMRoutine
    - cd $SAFELOCATION/NMRoutine/NeteaseMusicLyricProvider
    - rm -rf Packages/*

    - xcodebuild clean build
        CODE_SIGN_IDENTITY=""
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_ENTITLEMENTS=""
        CODE_SIGNING_ALLOWED="NO"
        MonkeyDevInstallOnProfiling="NO"
        MonkeyDevInstallOnAnyBuild="NO"
        MonkeyDevCopyOnBuild="NO"
        MonkeyDevClearUiCacheOnInstall="NO"
        MonkeyDevBuildPackageOnAnyBuild="YES"
        | xcpretty

    - cp Packages/*.deb $SAFELOCATION/artifacts/

    # QMRoutine
    - cd $SAFELOCATION/QQMusicRoutine/QQMusicLyricsProvider
    - rm -rf Packages/*

    - xcodebuild clean build
        CODE_SIGN_IDENTITY=""
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_ENTITLEMENTS=""
        CODE_SIGNING_ALLOWED="NO"
        MonkeyDevInstallOnProfiling="NO"
        MonkeyDevInstallOnAnyBuild="NO"
        MonkeyDevCopyOnBuild="NO"
        MonkeyDevClearUiCacheOnInstall="NO"
        MonkeyDevBuildPackageOnAnyBuild="YES"
        | xcpretty

    - cp Packages/*.deb $SAFELOCATION/artifacts/

    # BigBoss Context
    - cd $SAFELOCATION/BigBossConnect
    - rm -rf temp && mkdir temp
    - cd temp
    - cp $SAFELOCATION/SpringBoardInjector/DesktopLyricOverlay/Packages/*.zip .
    - cp $SAFELOCATION/NMRoutine/NeteaseMusicLyricProvider/Packages/*.zip .
    - cp $SAFELOCATION/QQMusicRoutine/QQMusicLyricsProvider/Packages/*.zip .
    - for i in *.zip; do unzip -o $i; done
    - cd ..
    - cp ./temp/Library/MobileSubstrate/DynamicLibraries/*.dylib ./nmlrc/Library/MobileSubstrate/DynamicLibraries/
    - cp ./temp/Library/MobileSubstrate/DynamicLibraries/*.plist ./nmlrc/Library/MobileSubstrate/DynamicLibraries/
    - cd nmlrc
    - dpkg-deb -Zgzip -b . ../nmlrc.deb
    - cd $SAFELOCATION
    - cp BigBossConnect/nmlrc.deb artifacts/

    # CLEAN UP JOBS
    - cd $SAFELOCATION
    - ls -la artifacts
    - for i in artifacts/*.deb; do dpkg -I $i; done

